### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ivanoats** [konsumer/gatsby-starter-drunkenblog#2]
Could you add a LICENSE file please? I'd love to use your Disqus comment. Thanks so much for blogging about this!

http://choosealicense.com

**Comment by ivanoats** [comment]
Sorry, just saw MIT in package.json.

**Comment by konsumer** [comment]
Yep. I try to keep the file count down for boilerplate stuff, but I'd be happy to publish it seperately with a LICENSE file, though, if that would be easier to use. I might recommend komments if you are starting with a new site, as it seemed a bit less buggy, and it loads a lot faster (no iframe, smaller code) and uses markdown so it fits better with a programming blog. Disqus seems really geared towards standard static sits. I lost a bunch of comments switching to komments, and it doesn't have as many features, but overall it seems to work a lot better.
